[build]
  # 构建命令
  command = "pnpm build"
  # 构建输出目录
  publish = "dist"

[build.environment]
  # Node.js 版本
  NODE_VERSION = "18"
  # 包管理器
  NPM_FLAGS = "--version"
  PNPM_VERSION = "9.14.4"

# 处理 SPA 路由的重定向规则
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = ["admin"]}

# 处理静态资源的缓存
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# 安全头部
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
